=== erikvanzijst/oldschool/work/network-management-0.4/src/configuration/configuration.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE network SYSTEM "configuration.dtd">

    <network>
    ...
    </network>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT distance (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT destination (address|routerId)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT source (address|routerId)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT connection (distance|destination|source)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT metric (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT addressElement (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT address (addressElement)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT interface (metric|address)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT managementAgent (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT managementDomain (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT managementKey (managementAgent|managementDomain)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT listenerPort (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT httpPort (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT httpPassword (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT httpUser (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT managementPort (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT host (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT administration (managementKey|listenerPort|httpPort|httpPassword|httpUser|managementPort|host)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT routerId (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT router (interface|administration|routerId)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT network (connection|router)*>

=== erikvanzijst/oldschool/work/network-management-0.4/src/configuration/simpleconfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE network SYSTEM "file:C:\\MarketXS\cvs\network-management\src\configuration\configuration.dtd">


<!--
    Document   : XMLDocument.xml
    Created on : 30 September 2003, 14:21
    Author     : Laurence Crutcher
    Description:
        Purpose of the document follows.
-->

<network>

<router>
<routerId>1</routerId>
<administration>

<host>localhost</host>
<managementPort>1095</managementPort>
<httpUser>administrator</httpUser>
<httpPassword>secret</httpPassword>
<httpPort>8082</httpPort>
<listenerPort>5050</listenerPort>
<managementKey>
<managementDomain>Test</managementDomain>
<managementAgent>testagent</managementAgent>
</managementKey>
</administration>

<interface>
<address>
<addressElement>1</addressElement>
<addressElement>2</addressElement>
</address>
<metric>
1
</metric>
</interface>

<interface>
<address>
<addressElement>1</addressElement>
<addressElement>1</addressElement>
</address>
<metric>
1
</metric>
</interface>
</router>

<router>
<routerId>2</routerId>
<administration>

<host>localhost</host>
<managementPort>1099</managementPort>
<httpUser>administrator</httpUser>
<httpPassword>secret</httpPassword>
<httpPort>8082</httpPort>
<listenerPort>5050</listenerPort>
<managementKey>
<managementDomain>Test</managementDomain>
<managementAgent>testagent</managementAgent>
</managementKey>
</administration>

<interface>
<address>
<addressElement>2</addressElement>
<addressElement>1</addressElement>
</address>
<metric>
2
</metric>
</interface>
</router>

<connection>
<source>
<routerId>
1
</routerId>
<address>
<addressElement>1</addressElement>
<addressElement>2</addressElement>
</address>
</source>

<destination>
<routerId>
2
</routerId>
<address>
<addressElement>2</addressElement>
<addressElement>1</addressElement>
</address>
</destination>

<distance>
1
</distance>
</connection>

</network>
