=== erikvanzijst/oldschool/work/network-management-0.4/dist/configuration.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE network SYSTEM "configuration.dtd">

    <network>
    ...
    </network>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Distance (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DestHost (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DestInterface (Address)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Connection (Distance|DestHost|DestInterface)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Metric (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT AddressElement (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Address (AddressElement)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SrcInterface (Connection|Metric|Address)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT interface (SrcInterface)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT management_agent (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT management_domain (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT management_key (management_agent|management_domain)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT listener_port (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT http_port (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT http_password (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT http_user (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT management_port (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT host (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT administration (management_key|listener_port|http_port|http_password|http_user|management_port|host)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ID (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT node (interface|administration|ID)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT network (node)*>

=== erikvanzijst/oldschool/work/network-management-0.4/dist/extraconfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE network SYSTEM "file:C:\\MarketXS\NetworkManagement\configuration\configuration.dtd">

<!--
    Document   : XMLDocument.xml
    Created on : 30 September 2003, 14:21
    Author     : Laurence Crutcher
    Description:
        Purpose of the document follows.
-->

<network>

<node>
<ID>3</ID>
<administration>

<host>localhost</host>
<management_port>1095</management_port>
<http_user>administrator</http_user>
<http_password>secret</http_password>
<http_port>8082</http_port>
<listener_port>5050</listener_port>
<management_key>
<management_domain>Test</management_domain>
<management_agent>testagent</management_agent>
</management_key>
</administration>
<interface>
<SrcInterface>
<Address>
<AddressElement>3</AddressElement>
<AddressElement>1</AddressElement>
</Address>
</SrcInterface>
<DestInterface>
<Address>
<AddressElement>1</AddressElement>
<AddressElement>2</AddressElement>
</Address>
</DestInterface>
<DestHost>
1
</DestHost>
<Distance>
1
</Distance>

</interface>
</node>

</network>

=== erikvanzijst/oldschool/work/network-management-0.4/dist/simpleconfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--<!DOCTYPE network SYSTEM "file:C:\\MarketXS\NetworkManagement\dist\configuration.dtd">-->


<!--
    Document   : XMLDocument.xml
    Created on : 30 September 2003, 14:21
    Author     : Laurence Crutcher
    Description:
        Purpose of the document follows.
-->

<network>

<node>
<ID>1</ID>
<administration>

<host>localhost</host>
<management_port>1095</management_port>
<http_user>administrator</http_user>
<http_password>secret</http_password>
<http_port>8082</http_port>
<listener_port>5050</listener_port>
<management_key>
<management_domain>Test</management_domain>
<management_agent>testagent</management_agent>
</management_key>
</administration>
<interface>
<SrcInterface>
<Address>
<AddressElement>1</AddressElement>
<AddressElement>2</AddressElement>
</Address>
<Metric>
1
</Metric>
<Connection>
<DestInterface>
<Address>
<AddressElement>2</AddressElement>
<AddressElement>1</AddressElement>
</Address>
</DestInterface>
<DestHost>
2
</DestHost>
<Distance>
1
</Distance>
</Connection>
</SrcInterface>

</interface>
<interface>
<SrcInterface>
<Address>
<AddressElement>1</AddressElement>
<AddressElement>1</AddressElement>
</Address>
<Metric>
1
</Metric>
<Connection>
<DestInterface>
<Address>
<AddressElement>4</AddressElement>
<AddressElement>1</AddressElement>
</Address>
</DestInterface>
<DestHost>
4
</DestHost>
<Distance>
1
</Distance>
</Connection>
</SrcInterface>

</interface>
</node>

<node>
<ID>2</ID>
<administration>

<host>localhost</host>
<management_port>1099</management_port>
<http_user>administrator</http_user>
<http_password>secret</http_password>
<http_port>8082</http_port>
<listener_port>5050</listener_port>
<management_key>
<management_domain>Test</management_domain>
<management_agent>testagent</management_agent>
</management_key>
</administration>
<interface>
<SrcInterface>
<Address>
<AddressElement>2</AddressElement>
<AddressElement>1</AddressElement>
</Address>
<Metric>
2
</Metric>
<Connection>
<DestInterface>
<Address>
<AddressElement>1</AddressElement>
<AddressElement>2</AddressElement>
</Address>
</DestInterface>
<DestHost>
1
</DestHost>
<Distance>
1
</Distance>
</Connection>
</SrcInterface>

</interface>
</node>
</network>
